name: Daily Duty Reminder

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        echo "当前工作目录: $PWD"
        echo "仓库目录结构:"
        ls -R
        pip install -r ./scripts/requirements.txt

    - name: Run reminder script
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        USER_OPENID: ${{ secrets.USER_OPENID }}
        TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
        USER_OPENIDS: "openid1,openid2,openid3"
      run: |
        python ./scripts/duty_reminder.py
